### ISSUE TITLE
Spin off: How to deal with window-load timing in bootstrapped extensions

### ISSUE THREAD

**Issue by jobisoft** [jikamens/userChromeJS#1]
I do not want to add more noise to the original thread. My correction was a direct answer to this remark:

> Also, your example code makes the assumption that during app startup the extension's startup() method will be called before the mail-startup-done event is generated. I'm not sure that assumption is any more reasonable than the opposite assumption, so the code has to be resilient to either possibility. My sample code is.

I will look at the addon tonight to learn what your window issue is.

**Comment by jikamens** [comment]
I don't have an issue. My add-on works just fine with my code.

The discussion in https://github.com/thundernest/developer-docs/pull/20 is not about an issue with my add-on, which works just fine, but rather about how we should document for other bootstrapped add-on maintainers how to ensure that code is executed at the appropriate time for all windows.

This discussion does not belong here. My add-on works just fine.

**Comment by jobisoft** [comment]
Ok, that was unexpected. I am just an add-on dev myself trying to help others. I am getting hit on by the Thunderbird Devs for trying to help addon devs and now I am also getting this response from an addon dev? 

If you have no issue with your add-on, why did you report, that something is not working?

I do not want to talk about tangential suggestions in the original thread, because so many people are on the CC list which I do not want to flood (because I got hit on for that the last time I did that).

**Comment by jikamens** [comment]
>If you have no issue with your add-on, why did you report, that something is not working?

I don't understand.

I did not report that something is not working.

I submitted a pull request to the Thunderbird developer docs suggesting improvements to the docs to cover an issue which I experienced _and fixed_ in my own add-ons after the change was made to get rid of install.rdf for bootstrapped add-ons.

How is that "reporting that something is not working?"

**Comment by jobisoft** [comment]
If I am allowed, I would like explain myself:

After you switched from install.rdf to manifest.json, you experienced an issue, that something was not working. That is what I referred to as not working.

Now it looks like that it is a timing issue which has been there all along, but is now more prominent. Some TB devs say "not new in generall" and propose to drop your pull request.

I would like to fully understand the issue and propose a simple solution which we could add to the doc. I personally think, the fix you propose is to complex. But it could of course be, that my simple solution is not global enough. But to understand that in detail, I wanted to look at the original code of yours that did not work in the latest daily. To be precise, i want to fix it with my solution and want to see, where it is failing.

Now all of this and explaining my alternative suggestion has nothing to do with your original pull request and since I have been hit on for posting tagential suggestions in similar threads, I wanted to move it to another place. But that was wrong again. Frustrating.

**Comment by jikamens** [comment]
I understand and appreciate that you are trying to be helpful.

However, I do not think you are being helpful.

I do not have more time or energy right now to explain why, so please be content with that.
