### ISSUE TITLE
Not compatible with Thunderbird 78

### ISSUE THREAD

**Issue by gabri25ele** [jikamens/userChromeJS#3]
Installed Thunderbird 78, userChromeJS seems not work ...
can we hope for an update?

**Comment by jikamens** [comment]
We're working on it.

**Comment by gabri25ele** [comment]
you are the best!

**Comment by jikamens** [comment]
Actually, Jorg (TB developer) did most of the work. I just need to clean it up and package it. Credit where credit is due!

**Comment by rossmeissl** [comment]
@jikamens just curious if you still plan to clean and package the new version! Thank you! 😀

**Comment by jikamens** [comment]
It's already done. The new version is available on addons.thunderbird.net.
