### ISSUE TITLE
how do i know if it's really working?

### ISSUE THREAD

**Issue by gabri25ele** [jikamens/userChromeJS#4]
I tried this
http://forums.mozillazine.org/viewtopic.php?f=28&t=3057347
but seems no work.

Can I see in the console if the extension is working?

**Comment by jikamens** [comment]
Please don't use GitHub issues for support. There's a support email address on the add-on's home page on addons.thunderbird.net.

You can put `console.log("whatever");` statements into your userChrome.js to log to the console. If you put multiple such statements in different parts of your file you can see which parts of the file are and aren't executing, e.g., at a minimum, put a log statement at the beginning and end of the file to confirm that it makes it all the way through without a syntax error/
