### ISSUE TITLE
Plugin broken with 102.6.1 - won't load scripts "disabled internally"

### ISSUE THREAD

**Issue by nneul** [jikamens/userChromeJS#6]
This error shows up in error console:

![image](https://user-images.githubusercontent.com/828492/210573061-32915fec-07cb-4294-b65e-f639e8c6bf28.png)

I've been using for a very simple 'add some custom keyboard mappings' functionality (adding control-D for message deletion in my case). 

Haven't found anything to address this yet, but filing here to track and in case anyone else has any ideas.

**Comment by numeratorjik** [comment]
That error you're seeing there has nothing to do with the functionality of my add-on. There is no reference to that URL anywhere in my add-on's source code. Furthermore the add-on is working fine for me in TB 102.6.1, so I'm not sure what problem you're running into.

**Comment by nneul** [comment]
Interesting. Symptom I'm seeing after upgrade this morning was my shortcuts no longer work. Possible that message about userChromeJS is a red herring.  OH, never mind, it likely is a complete red herring - that's probably from me opening the plugin page within thunderbird browser window when checking for any updates/github link/etc.

This is the content of my file that's no longer appearing to work. Must be something specific to my code and/or changes in TB itself and NOT the plugin at all. 

```
function userChromeUnbindKey(keyset_id, key_id) {
    var keyset = document.getElementById(keyset_id);
    if (! keyset) {
        console.log("Could not find keyset " + keyset_id);
        return;
    }
    var key = document.getElementById(key_id);
    if (! keyset) {
        console.log("Could not find key " + key_id);
        return;
    }
    keyset.removeChild(key);
}

function userChromeBindKey(keyset_id, key, key_id, modifiers, command, observes) {
    var keyset = document.getElementById(keyset_id);
    if (! keyset) {
        console.log("Could not find keyset " + keyset_id);
        return;
    }
    var elt = document.createXULElement("key");
    if (key)
        elt.setAttribute("key", key);
    if (key_id)
        elt.setAttribute("key_id", key);
    if (modifiers)
        elt.setAttribute("modifiers", modifiers);
    if (command)
        elt.setAttribute("oncommand", command);
    if (observes)
        elt.setAttribute("observes", observes);
    keyset.appendChild(elt);
}

if (location == "chrome://messenger/content/messenger.xhtml")
{
    userChromeBindKey("mailKeys", "d", "key_to_customdelete", "control",
                      "goDoCommand('cmd_delete');");
}
```

**Comment by nneul** [comment]
And double never mind. I just restarted TB completely and it's working fine. Smh. Sorry for the noise!

**Comment by jikamens** [comment]
If you haven't tried simply restarting Thunderbird, see if that helps. I've run into situations where after an upgrade to TB or the add-on it doesn't work on the first restart. I haven't been motivated enough to debug. :-/

**Comment by jikamens** [comment]
lol jinx
