### ISSUE TITLE
Add Support for Calendar New Event window

### ISSUE THREAD

**Issue by Hiche3** [jikamens/userChromeJS#7]
If interested, here is a potential solution:

* experiments.js , replace line 44:

```
urls.push("chrome://calendar/content/calendar-event-dialog.xhtml");
// Adds a listener to detect new windows.
```

**Comment by jikamens** [comment]
Thanks, new version uploaded to addons.thunderbird.net with this fix.

Change is in https://github.com/Extended-Thunder/userChromeJS. I'm going to archive this repository and make it read-only so people stop filing issues in the wrong place.
